### ISSUE TITLE
Problems with usernames

### ISSUE THREAD

**Issue by Bennano** [Eidenz/Nextcloud-Talk-Desktop#2]
by using your Application i discoverd, that its not possible to set E-Mails as usernames. 
When using the ´@´ in a username it causes Problems. 
Maybe this is a minor thing that can befixed easy.

Greetings

**Comment by Eidenz** [comment]
Hello,

Could you please give more details? I'm can't replicate your issue, using emails works fine for me.

The login part is handled by Nextcloud, not my app. Are you sure you can login to your nextcloud instance (via your own browser) with your email?

**Comment by Bennano** [comment]
yes, i can login to my nextcloud instance via browser with my email. but when login via the app also using my email, my mail address gets changed from firstname.lastname@provider.de to firstname.lastname%40provider.de and then i receive an error telling me that my app token login name does not match which makes sense, since my correct login data is with @ and not %40. the change of the name is shown in the file myResources.

**Comment by Eidenz** [comment]
Issue should be fixed in commit d5423f6
