### ISSUE TITLE
App doesnt show the propmt to allow or deny permission to mic and webcam

### ISSUE THREAD

**Issue by Bennano** [Eidenz/Nextcloud-Talk-Desktop#3]
Hi ,

I encountered an issue with the desktop app for windows. 
When I login via browser I have to give my permission for the site to access my mic and webcam. But when I use the app, it doesnt show the prompt to allow or deny permission to mic and webcam. When I go to the settings for mic and webcam in the app I can select either "none" or "standard". If I select the latter it tells me access denied.
When I go to the windows-settings for the camera, nextcloud isnt listed as one of the apps that has access to the camera - idk if this helps.
Do you know this problem and/or do you know how to fix it or rather give my permission to access? Thanks in advance

**Comment by Eidenz** [comment]
I'll investigate this

**Comment by Eidenz** [comment]
Sorry for the delay. Issue should be fixed with commit d5423f6

I uploaded a new release 1.3

**Comment by Bennano** [comment]
Thank you very much for your work, its works perfectly fine now. We are very happy to have found the app!
