### ISSUE TITLE
No setup dialog with release 1.4

### ISSUE THREAD

**Issue by LucaOverflow** [Eidenz/Nextcloud-Talk-Desktop#4]
Hi @Eidenz,

first up: GREAT WORK. You fixed the biggest flaw in Talk all by yourself :)

When setting up your app i encountered a little problem:

If I want to run the 1.4 release nothing happens. No window open, no runnung process, nothing...
Version 1.3 worked however. So I copied the contents from the new release in the old application folder and that did the trick.
Now 1.4 ist working.
I'm not sure if this has to do with the setup process or something else, but if you have further questions I'll do my best to help you.

I've had the same behavior on two machines, both running the latest W11 stable release and similar other Software in the background.

**Comment by Eidenz** [comment]
Hi,

Thanks for your feedback.

I acknowledge the issue when running without an existing config. This is likely due to a library failing to compile on my end. I will be fixing the issue within the day.

**Comment by Eidenz** [comment]
I replaced the package with the new fix and the setup is now showing on version 1.4.

You can keep using your modified 1.3 package as only the `Talk.exe` file actually changed, so putting the one from 1.4 into the 1.3 folder is perfectly fine.
